## porta do servico ##
server.port=8082

### Configuracoes do banco de dados ##
spring.datasource.url=jdbc:postgresql://localhost:5432/tracking
spring.datasource.username=postgres
spring.datasource.password=matheusted19

### Configuracoes do JPA ##
spring.jpa.hibernate.ddl-auto=update

## Configuracoes do RabbitMQ ##
spring.rabbitmq.addresses=amqps://obfbyfbm:Lgh6N_fbi8x0bRCeYHD4ybcwJLMo3ys5@leopard.lmq.cloudamqp.com/obfbyfbm
broker.queue.processamento.name=exchange.processamento

